spring:
  application:
    name: family-memoirs
  datasource:
    url: jdbc:postgresql://172.16.4.16:5432/memoirs
    username: nekro_agent
    password: nekro_agent
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: logs/application.log
upload:
  userAvatarLocation: uploads/avatars/user
  userAvatarUrlBase: /teller/avatar