spring:
  application:
    name: family-memoirs
  datasource:
    url: jdbc:postgresql://localhost:5432/memoirs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    # show-sql: true
logging:
  file:
    name: logs/application.log
